<?php 
	echo $this->doctype() 
?>
<html> 
<head>
<?php
	echo $this->headMeta(); 
	echo $this->headTitle();
	echo $this->headStyle();
	$this->headScript()->appendFile($this->baseUrl().'/js/jquery/js/jquery-1.4.2.min.js','text/javascript');
	$this->headScript()->appendFile($this->baseUrl().'/js/jquery/js/jquery-ui-1.8.4.custom.min.js','text/javascript');	
	$this->headScript()->appendFile($this->baseUrl().'/js/jquery/js/jquery.ui.datepicker-pt-BR.js','text/javascript');	
	$this->headScript()->appendFile($this->baseUrl().'/js/jquery/js/jquery.positionBy.js','text/javascript');
	$this->headScript()->appendFile($this->baseUrl().'/js/jquery/js/jquery.bgiframe.js','text/javascript');
	$this->headScript()->appendFile($this->baseUrl().'/js/jquery/js/jquery.jdMenu.js','text/javascript');
	$this->headScript()->appendFile($this->baseUrl().'/js/jquery/js/jquery.maskedinput-1.2.2.min.js','text/javascript');
	$this->headScript()->appendFile($this->baseUrl().'/js/standard.js','text/javascript');
	$this->headLink()->appendStylesheet($this->baseUrl().'/styles/jquery.jdMenu.css');
	$this->headLink()->appendStylesheet($this->baseUrl().'/styles/jdMenu.slate.css');
	$this->headLink()->appendStylesheet($this->baseUrl().'/styles/master.css');
	$this->headLink()->appendStylesheet($this->baseUrl().'/js/jquery/css/redmond/jquery-ui-1.8.4.custom.css');
	echo $this->headScript();
	echo $this->headLink();
	
	
	
?>	
</head> 
<body class="soria">
	<div id="header">
		<h1><?php echo $this->placeholder('title') ?></h1>
	</div>
	<?php if ($this->navigation()->hasPages()):?>
		<div id="menu">
			<?php	$this->navigation()->menu()->setULClass('jd_menu jd_menu_slate'); 
			echo $this->navigation ()->menu ();?>
		</div>
	<?php endif;?>
	<?php echo $this->flashMessenger();?>	
	<div id="container">
		<?php echo $this->layout()->content ?>
	</div>
	<div id="footer"><?php echo $this->placeholder('footer') ?>
	</div>
</body>
</html>
