<script type="text/javascript">
<!--
    $(document).ready(function() {
        $("#add").click(function(){location.href = '<?php echo $this->url(array('action'=>'add')); ?>'});
        $("#tblAcademias tr:nth-child(even)").addClass("odd");
    });
-->
</script>
<style>
<!--
tr.odd {
  background: #B9D3EE;
}
th {
	background: #B9D3CC;
}
-->
</style>
<table style="margin-left:1%;width: 98%;background-color: #EAF6FF;">
	<tr>
		<th colspan="2" style="background-color: #BEBEBE;">Classificação da pressão arterial de adultos com 18 anos em repouso</th>
	</tr>
	<tr>
		<td colspan="2">
		<?php
		if (isset ( $this->paginator )) :
			?>
        	<table id="tblAcademias"
				style="margin-left: 3%; margin-right: 3%; width: 94%; margin-top: 1%; margin-bottom: 1%; border-collapse: collapse; border-spacing: 3em">
			<thead>
				<tr>
					<th rowspan="2"
						style="border: 1px solid black; text-align: center;">Categoria</th>
					<th colspan="2"
						style="border: 1px solid black; text-align: center;">Sistólica</th>
					<th colspan="2"
						style="border: 1px solid black; text-align: center;">Diastólica</th>
					<th rowspan="2"
						style="border: 1px solid black; text-align: center;">Área de trabalho do<br/>Profissional de<br/>Educação Física</th>						
					<th rowspan="2"
						style="border: 1px solid black; text-align: center;"></th>
						
				</tr>
				<tr>
					<th
						style="border: 1px solid black; text-align: center;">Limite Inferior</th>
					<th
						style="border: 1px solid black; text-align: center;">Limite Superior</th>
					<th
						style="border: 1px solid black; text-align: center;">Limite Inferior</th>
					<th
						style="border: 1px solid black; text-align: center;">Limite Superior</th>
				</tr>
            </thead>
        		<?php
					foreach ( $this->paginator as $data ) :
				?>
            	<tr>
				<td style="border: 1px solid black; text-align: center;"><?php echo $data ['situa_categ'];?></td>
				<td style="border: 1px solid black; text-align: center;"><?php echo $data ['pres_sisto_inf'];?></td>
				<td style="border: 1px solid black; text-align: center;"><?php echo $data ['pres_sisto_sup'];?></td>
				<td style="border: 1px solid black; text-align: center;"><?php echo $data ['pres_diast_inf'];?></td>
				<td style="border: 1px solid black; text-align: center;"><?php echo $data ['pres_diast_sup'];?></td>
				<td style="border: 1px solid black; text-align: center;"><?php echo $data ['situa_profis_edc_fis'];?></td>
				<td style="border: 1px solid black; text-align: center;">
					<a href="<?php echo $this->url ( array ('action' => 'edit', 'cod_prss_art' => $data ['cod_prss_art'] ) );?>">Alterar</a> /
					<a href="<?php echo $this->url ( array ('action' => 'delete', 'cod_prss_art' => $data ['cod_prss_art'] ) );?>">Excluir</a>					
				</td>
				
			</tr>
			<?php endforeach;?>           	
        	</table>
        </td>
	</tr>
	<tr>
		<td align="center" colspan="2">
            <?php echo $this->paginationControl ( $this->paginator, 'Sliding', 'index/paginador.phtml' );?>
        </td>
	</tr>
		<?php endif;?>
	<tr>
		<td colspan="2" align="right" nowrap="nowrap"><input type="button" id="add" value="Nova Classificação" /></td>
	</tr>
</table>
