<script type="text/javascript">
<!--
    $(document).ready(function() {
        $("#add").click(function(){location.href = '<?php echo $this->url(array('action'=>'add')); ?>'});
        $("#tblAcademias tr:nth-child(even)").addClass("odd");
    });
-->
</script>
<style>
<!--
tr.odd {
  background: #B9D3EE;
}
th {
	background: #B9D3CC;
}
-->
</style>
<table style="margin-left:1%;width: 98%;background-color: #EAF6FF;">
	<tr>
		<th colspan="2" style="background-color: #BEBEBE;">Unidades Básicas de Saúde</th>
	</tr>
	<tr>
		<td colspan="2">
		<?php
			if (isset ( $this->paginator )) :
			?>
        	<table id="tblAcademias"
				style="margin-left: 3%; margin-right: 3%; width: 94%; margin-top: 1%; margin-bottom: 1%; border-collapse: collapse; border-spacing: 3em">
        		<?php
        			$rg = '';
					foreach ( $this->paginator as $data ) :
					$regional = $data->findParentRow('Model_Regionais');
					if ($rg <> $data ['cod_regi']):
				?>
				<tr><th colspan="3" style="border: 1px solid black;"><?php echo $regional['desc_regi'];?></th></tr>
				<tr>
					<th
						style="border: 1px solid black; text-align: left;">Código</th>
					<th
						style="border: 1px solid black; text-align: left;">Nome UBS</th>
					<th
						style="border: 1px solid black; text-align: left;"></th>
							
				</tr>
				<?php $rg = $data ['cod_regi']; endif;?>
				
				
            	<tr>

				<td style="border: 1px solid black;"><?php echo $data ['cod_unsa'];?></td>
				<td style="border: 1px solid black;"><?php echo utf8_encode($data ['desc_unsa']);?></td>
				<td style="border: 1px solid black;">
					<a href="<?php echo $this->url ( array ('action' => 'edit', 'cod_unsa' => $data ['cod_unsa'] ) );?>">Alterar</a> /
					<a href="<?php echo $this->url ( array ('action' => 'delete', 'cod_unsa' => $data ['cod_unsa'] ) );?>">Excluir</a>					
				</td>
				
			</tr>
			<?php endforeach;?>           	
        	</table>
        </td>
	</tr>
	<tr>
		<td align="center" colspan="2">
            <?php echo $this->paginationControl ( $this->paginator, 'Sliding', 'index/paginador.phtml' );?>
        </td>
	</tr>
		<?php endif;?>
	<tr>
		<td colspan="2" align="right" nowrap="nowrap"><input type="button" id="add" value="Nova Unidade" /></td>
	</tr>
</table>
